#page title
page_title                                : Nexgenify Apps                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #364709193                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://nexgenifyapps.github.io/ExpenseTracker/privacy-policy                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :  Budget Coach - Expense Tracker                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Manage your finances effortlessly with Expense Tracker. Track spending, set budgets, and save money with ease. Your go-to app for budgeting and financial planning!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nexgenify Apps                                
your_link                                 : https://nexgenify.co                     
your_city                                 : Universe                                
email_address                             : hello@nexgenify.co
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : nexgenifyapps
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Quick and Easy Expense Recording
    description                           : Start by recording your first expense with just a few taps. Our intuitive interface ensures that logging your expenses is a breeze, allowing you to stay on top of your finances without any hassle.
    fontawesome_icon_name                 : magic
    
  - title                                 : Visual Financial Insights
    description                           : Gain valuable insights into your spending with our visual graphs. These charts provide a clear overview of your monthly expenditures, highlighting any unusual spikes or drops. This feature helps you identify spending patterns and make informed financial decisions.
    fontawesome_icon_name                 : eye

  - title                                 : Customizable Transaction Filters
    description                           : Easily filter your transactions with customizable filters. Whether you want to view expenses by category, amount, or date, our app allows you to quickly find and review specific transactions, ensuring you have detailed control over your financial data.
    fontawesome_icon_name                 : filter

  - title                                 : Effortless Transaction Deletion
    description                           : Managing your transactions is simple with our easy delete feature. Just swipe to delete any transaction record, keeping your financial data clean and up-to-date.
    fontawesome_icon_name                 : eraser
  
  - title                                 : Detailed Budget Patterns
    description                           : Get a comprehensive view of your budget patterns for each month. Our detailed breakdowns show where your money is going, helping you stay within your budget and identify areas where you can save.
    fontawesome_icon_name                 : star

  - title                                 : Enhanced Security with App Lock
    description                           : Keep your financial information secure with our App Lock feature. Choose your preferred security mode to ensure that only you have access to your expense records, providing peace of mind and protecting your privacy.
    fontawesome_icon_name                 : lock

  - title                                 : User-Friendly Design
    description                           : Designed with simplicity in mind, making it easy for anyone to manage their finances, regardless of their financial expertise.
    fontawesome_icon_name                 : mobile

  - title                                 : Dark Mode Support
    description                           : Enjoy a sleek, modern interface that’s easy on the eyes. Switch to dark mode for a better viewing experience, especially in low light conditions.
    fontawesome_icon_name                 : moon

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimg.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#8e1cfa"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#8e1cfa"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  
# Exclude these files from your production _site
exclude:
  - vendor
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
